### ISSUE TITLE
CottonClientCommandSource causes ClassCastException

### ISSUE THREAD

**Issue by SteveKunG** [CottonMC/ClientCommands#5]
**The Bug**
```
java.lang.ClassCastException: net.minecraft.client.network.ClientCommandSource cannot be cast to io.github.cottonmc.clientcommands.CottonClientCommandSource
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66)
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357)
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347)
	at net.minecraft.client.gui.screen.ChatScreen.updateCommand(ChatScreen.java:189)
	at net.minecraft.client.gui.screen.ChatScreen.onChatFieldChanged(ChatScreen.java:96)
	at net.minecraft.client.gui.widget.TextFieldWidget.onChanged(TextFieldWidget.java:147)
	at net.minecraft.client.gui.widget.TextFieldWidget.addText(TextFieldWidget.java:141)
	at net.minecraft.client.gui.widget.TextFieldWidget.charTyped(TextFieldWidget.java:346)
	at net.minecraft.client.gui.ParentElement.charTyped(ParentElement.java:82)
	at net.minecraft.client.Keyboard.method_1458(Keyboard.java:370)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:430)
	at net.minecraft.client.Keyboard.onChar(Keyboard.java:370)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at net.minecraft.client.util.Window.pollEvents(Window.java:451)
	at net.minecraft.client.util.Window.setFullscreen(Window.java:312)
	at net.minecraft.client.MinecraftClient.updateDisplay(MinecraftClient.java:952)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:916)
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:386)
	at net.minecraft.client.main.Main.main(Main.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**To Reproduce**
1. Just running the game with latest API in the dev environment + command
https://github.com/SteveKunG/Indicatia/blob/1.14-fabric/src/main/java/stevekung/mods/indicatia/command/AFKCommand.java

**Current Version**
cotton-client-commands-0.4.0+1.14.2

**Comment by Juuxel** [comment]
Could you try the new `0.4.1+1.14.2` build?

**Comment by SteveKunG** [comment]
Confirm fixed, Thanks!

**Comment by SteveKunG** [comment]
Also could you push new version on CurseForge please?

**Comment by Juuxel** [comment]
Just pushed it.
